import { generate } from "./generate";
import { env } from "process";
import * as client from "./util/client";
import { createClientConfig } from "./util/client";
import { createConfig } from "./util/config";
import getAppsResponse from "./__tests__/get-apps-response.json";
import getFormFieldsResponse from "./__tests__/get-form-fields-response.json";
import p from "../package.json";

describe("generate", () => {
  test("succeed", async () => {
    jest.spyOn(client, "Client").mockImplementationOnce(() => {
      return {
        getApps: () => getAppsResponse.apps,
        getFormFields: () => getFormFieldsResponse,
      } as unknown as client.Client;
    });

    const result = await generate({
      params: {},
      config: createConfig(),
      clientConfig: createClientConfig(),
    });

    expect(result).toBe(actual);
  });
});

const actual = `
/* tslint:disable */
/* eslint-disable */
/**
 * This file is auto generated by ${p.name} version ${p.version}.
 * Don\`t edit this file manually.
 * @see ${p.homepage}
 */
import { Calc, Category, CheckBox, CreatedTime, Creator, Date, DateTime, Dropdown, File, GroupSelect, ID, Link, Modifier, MultiLineText, MultiSelect, Number, OrganizationSelect, RadioButton, RecordNumber, Revision, RichText, SingleLineText, Status, StatusAssignee, Subtable, Time, UpdatedTime, UserSelect } from "@kintone/rest-api-client/lib/KintoneFields/types/field";
/**
* KintoneApp54Record
* 入力項目テストアプリ
* id: 54
* revision: 4
* @see ${env.KINTONE_BASE_URL}/k/54/
*/
export interface KintoneApp54Record {
    /**
    * ID
    * @type ID
    */
    "__ID__": ID;
    /**
    * Revision
    * @type Revision
    */
    "__REVISION__": Revision;
    /**
    * カテゴリー
    * @type Category
    */
    "カテゴリー": Category;
    /**
    * グループ選択
    * @type GroupSelect
    */
    "グループ選択": GroupSelect;
    /**
    * ステータス
    * @type Status
    */
    "ステータス": Status;
    /**
    * チェックボックス
    * @type CheckBox
    */
    "チェックボックス": CheckBox;
    /**
    * テーブル
    * @type Subtable
    */
    "テーブル": Subtable<{
        /**
        * 文字列 (1行)
        * 文字列__1行__Table
        * @type SingleLineText
        */
        "文字列__1行__Table": SingleLineText;
    }>;
    /**
    * ドロップダウン
    * @type Dropdown
    */
    "ドロップダウン": Dropdown;
    /**
    * ユーザー選択
    * @type UserSelect
    */
    "ユーザー選択": UserSelect;
    /**
    * ラジオボタン
    * @type RadioButton
    */
    "ラジオボタン": RadioButton;
    /**
    * リッチエディター
    * @type RichText
    */
    "リッチエディター": RichText;
    /**
    * リンク
    * @type Link
    */
    "リンク": Link;
    /**
    * ルックアップ
    * @type Number
    */
    "ルックアップ": Number;
    /**
    * レコード番号
    * @type RecordNumber
    */
    "レコード番号": RecordNumber;
    /**
    * 作成日時
    * @type CreatedTime
    */
    "作成日時": CreatedTime;
    /**
    * 作成者
    * @type Creator
    */
    "作成者": Creator;
    /**
    * 作業者
    * @type StatusAssignee
    */
    "作業者": StatusAssignee;
    /**
    * 数値
    * @type Number
    */
    "数値": Number;
    /**
    * 文字列 (1行)
    * 文字列__1行_
    * @type SingleLineText
    */
    "文字列__1行_": SingleLineText;
    /**
    * 文字列 (複数行)
    * 文字列__複数行_
    * @type MultiLineText
    */
    "文字列__複数行_": MultiLineText;
    /**
    * 日付
    * @type Date
    */
    "日付": Date;
    /**
    * 日時
    * @type DateTime
    */
    "日時": DateTime;
    /**
    * 時刻
    * @type Time
    */
    "時刻": Time;
    /**
    * 更新日時
    * @type UpdatedTime
    */
    "更新日時": UpdatedTime;
    /**
    * 更新者
    * @type Modifier
    */
    "更新者": Modifier;
    /**
    * 添付ファイル
    * @type File
    */
    "添付ファイル": File;
    /**
    * 組織選択
    * @type OrganizationSelect
    */
    "組織選択": OrganizationSelect;
    /**
    * 複数選択
    * @type MultiSelect
    */
    "複数選択": MultiSelect;
    /**
    * 計算
    * @type Calc
    */
    "計算": Calc;
}
`.trimStart();
